---
title: "NY ticks"
author: "Iñaki Piñas"
date: "2024-10-08"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r  load-data}
rm(list=ls())
setwd("C:/Users/ipsad/OneDrive/Escritorio/Eco-epidemiology")
library(ggplot2)
library(gridExtra)
library(dplyr)
library(knitr)
library(kableExtra)
library(FactoMineR)
library(factoextra)
library(corrplot)
library(missMDA)
library(cluster)
library(vcd)
library(logistf)
library(MuMIn)
library(Hmisc)
library(scales)
library(tidyverse)
library(dagitty)

options(scipen = 999)

datos<- read.csv("C:/Users/ipsad/OneDrive/Escritorio/Eco-epidemiology/SI_yard.csv", header=T, sep=";", dec=",")

```

## Pre-process data:

Definimos las variables categóricas y factorizamos.

```{R  process}

cat_vars<- c("House.ID", "Address", "Park", "Neighborhood", "Ticks","Lawn", "Log.brush", "Wood", "Vegetable", "Birdfeeder", "Chicken", "Fence", "Play", "Seating", "Wall", "Compost.bin", "Trashcan", "Food.shelter", "type_edge")
#Convert cat_vars--> Factors
datos[cat_vars] <- lapply(datos[cat_vars], as.factor)

```

# Análisis descriptivo:

## Variables categóricas: variables against the presence of ticks

```{R Filter_data__Y}
#Dentro del nivel de infectados o no factorizamos estableciendo el 0 para no infectados y el 1 para infectados.

datos$Ticks_label <- factor(datos$Ticks, levels = c("N", "Y"), labels = c("NO", "YES"))

#Seleccionamos las variables categóricas que nos interesan:

categorical_variables <- setdiff(cat_vars,c("House.ID", "Address","Park","Neighborhood", "Ticks"))

#Representamos los datos en función de si están o no infectados

infection_bar_plot <-function(datos, categorical_variables, target_var) {
  datos <- datos[!is.na(datos[[categorical_variables]]), ]
  ggplot(datos, aes_string(x = target_var, fill = categorical_variables)) +
    geom_bar(position = "fill") +
    scale_y_continuous(labels = scales::percent_format()) +
    labs(y = NULL, fill = categorical_variables, x = "Infestation") +
    theme_minimal() +
    theme(legend.position = "none",
              plot.title = element_text(size = 8),
              axis.title.x = element_text(size = 8),
              axis.title.y = element_text(size = 8),
              axis.text.x = element_text(size = 7),
              axis.text.y = element_text(size = 7)
            ) +
    ggtitle(categorical_variables)
}


#Creamos una lista que recoja todas las gráficas de cada variable:

cat_plots <-list()

#Creamos el futloop:

for (var in categorical_variables) {
  cat_plots[[var]] <- infection_bar_plot(datos, var, "Ticks_label")
}
grid.arrange(grobs=cat_plots, ncol=5, nrow=4)
```

### Distribución (tabla de contingencia) y mostramos las proporciones:

```{R Proportions}
contingency_results <- data.frame(Variable = character(),
                                  Category = character(),
                                  No_Infestation = numeric(),
                                  Yes_Infestation = numeric(),
                                  stringsAsFactors = FALSE)
datos$type_edge2 <- ifelse(datos$type_edge == "2", "3", datos$type_edge)
datos$type_edge2<-ifelse(datos$type_edge2=="4", NA, datos$type_edge2)
table(datos$type_edge,datos$type_edge2)
for (var in categorical_variables) {
 
   # Create a contingency table
  contingency_table <- table(datos[[var]], datos$Ticks_label)
  
  # Calculate proportions
  prop_table <- prop.table(contingency_table, margin = 2)
  
  # Store results with proportions
  for (level in rownames(contingency_table)) {
    contingency_results <- rbind(contingency_results, data.frame(
      Variable = var,
      Category = level,
        No_Infestation = ifelse("NO" %in% colnames(prop_table), prop_table[level, "NO"], 0),  # Ajustar según etiquetas
      Yes_Infestation = ifelse("YES" %in% colnames(prop_table), prop_table[level, "YES"], 0)   # Ajustar según etiquetas
    )) 
  }
}
```

### Resultados en formato tabla

```{R Resultados}
contingency_results %>%
  mutate(No_Infestation = scales::percent(No_Infestation, accuracy = 0.1),
         Yes_Infestation = scales::percent(Yes_Infestation, accuracy = 0.1)) %>%
  kable("html", col.names = c("Variable", "Category", "No Infestation", "Yes Infestation"), align = "c") %>%
  kable_styling(full_width = FALSE, position = "left", 
                bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, color = "black") %>%
  column_spec(2, color = "black") %>%
  column_spec(3, color = "black") %>%
  column_spec(4, color = "black") %>%
  row_spec(0, bold = TRUE, color = "black")
```

### Test estadístico (Fisher) para cada variable categórica:

```{R Fisher test}
# Initialize an empty data frame to store results

fisher_results <- data.frame(Variable = character(),
                             p_value = numeric(),
                             stringsAsFactors = FALSE)

# Ejecutar el test exacto de Fisher para cada variable categórica

for (var in categorical_variables) {
  
# Crear la tabla de contingencia
  
  contingency_table <- table(datos[[var]], datos$Ticks_label)
  
# Verificar si la tabla es de tamaño 2x2
  
  if (nrow(contingency_table) == 2 && ncol(contingency_table) == 2) {
    # Si es una tabla 2x2, realizar el test
    test_result <- fisher.test(contingency_table)
    
# Almacenar los resultados en el dataframe
    
    fisher_results <- rbind(fisher_results, data.frame(Variable = var, p_value = test_result$p.value))
  } 
}

# Agregar la significancia en función del valor p

fisher_results <- fisher_results %>%
  mutate(Significance = case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ ""
  ))

# Formatear y mostrar los resultados como tabla

fisher_results %>%
  mutate(p_value = formatC(p_value, format = "f", digits = 4)) %>%
  kable("html", col.names = c("Variable", "P-value", "Significance"), align = "c") %>%
  kable_styling(full_width = FALSE, position = "left", 
                bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, color = "black") %>%
  column_spec(2, color = "black") %>%
  column_spec(3, bold = TRUE, color = "red") %>%
  row_spec(which(fisher_results$Significance != ""), bold = TRUE) %>%
  row_spec(0, bold = TRUE, color = "black") 
```

## Variables numéricas:

### Distribución (diagrama violín) y presentación en formato tabla:

```{R Var_numericas 1}

# Function to create violin plots with jittered points

create_violin_plot <- function(data, var_num, target_var) {
 
   ggplot(data, aes_string(x = target_var, y = var_num, fill = target_var)) +
    geom_violin(trim = FALSE) +
    geom_jitter(width = 0.2, size = 0.6, alpha = 0.6) +
    labs(y = var_num, fill = target_var, x = target_var) +
    theme_minimal() +
    theme(
      legend.position = "none",
      plot.title = element_text(size = 8),
      axis.title.x = element_text(size = 8),
      axis.title.y = element_text(size = 8),
      axis.text.x = element_text(size = 7),
      axis.text.y = element_text(size = 7)
    ) +
    ggtitle(var_num)
}

# Create list of numeric variables to visualize

var_num1<-c("Number.tubes", "Number.tubes.peromyscus","Number.tubes.insectivore", "Number.tubes.vole", "Number.tubes.raccoon", "Number.tubes.chipmunk", "Woodchuck_VisR", "Deer_VisR","Raccon_VisR", "Cat_VisR","Possum_VisR", "Skunk_VisR", "Squirrel_VisR", "Acres")

for (var in var_num1) {
  # Verifica la tabla de contingencia para cada variable numérica
  print(var)  # Muestra el nombre de la variable actual
  print(table(datos$Ticks_label, datos[[var]]))  # Muestra la tabla de contingencia
}
# Create a list to store the plots
num_plots1 <- list()

# Create plots for each numeric variable and store in the list
for (var in var_num1) {
  num_plots1[[var]] <- create_violin_plot(datos, var, "Ticks")
}

# Arrange the plots in a 4x4 grid
grid.arrange(grobs = num_plots1, ncol = 5, nrow = 3)

```

```{R var_numericas 2}

var_num2<-c("ApproxMOrnamentals", "Fencing.yard.", "ApproxMherbaceous","ApproxMnonherbaceous","ApproxMweeds","ApproxMevergreen","ApproxMgrass", "prop.grass", "prop.shrub", "prop.lowcan", "prop.highcan", "prop.bare", "prop.imperv")

for (var in var_num2) {
  # Verifica la tabla de contingencia para cada variable numérica
  print(var)  # Muestra el nombre de la variable actual
  print(table(datos$Ticks_label, datos[[var]]))  # Muestra la tabla de contingencia
}
num_plots2 <- list()
for (var in var_num2) {
  num_plots2[[var]] <- create_violin_plot(datos, var, "Ticks")
}

# Arrange the plots in a 4x4 grid
grid.arrange(grobs = num_plots2, ncol = 5, nrow = 3)

```

### Test estadístico (Wilcox-test):

```{R Wilcox_test}
# Inicializa el data frame vacío para los resultados
results <- data.frame(Variable = character(), p_value = numeric(), stringsAsFactors = FALSE)

# Variable fencing_yard
test_result_fencing.yard <- wilcox.test(datos$Fencing.yard. ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "fencing_yard", p_value = test_result_fencing.yard$p.value))

# Variable I
test_result_I <- wilcox.test(datos$I ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "I", p_value = test_result_I$p.value))

# Variable H
test_result_H <- wilcox.test(datos$H ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "H", p_value = test_result_H$p.value))

# Variable A
test_result_A <- wilcox.test(datos$A ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "A", p_value = test_result_A$p.value))

# Variable Number.tubes.with.hair
test_result_Number.tubes.with.hair <- wilcox.test(datos$Number.tubes.with.hair ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Number.tubes.with.hair", p_value = test_result_Number.tubes.with.hair$p.value))

# Variable Number.tubes
test_result_Number.tubes <- wilcox.test(datos$Number.tubes  ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Number.tubes", p_value = test_result_Number.tubes$p.value))

# Variable Number.tubes.peromyscus
test_result_Number.tubes.peromyscus <- wilcox.test(datos$Number.tubes.peromyscus ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Number.tubes.peromyscus", p_value = test_result_Number.tubes.peromyscus$p.value))

# Variable Number.tubes.insectivore
test_result_Number.tubes.insectivore <- wilcox.test(datos$Number.tubes.insectivore ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Number.tubes.insectivore", p_value = test_result_Number.tubes.insectivore$p.value))

# Variable Number.tubes.vole
test_result_Number.tubes.vole <- wilcox.test(datos$Number.tubes.vole ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Number.tubes.vole", p_value = test_result_Number.tubes.vole$p.value))

# Variable Number.tubes.raccoon
test_result_Number.tubes.raccoon <- wilcox.test(datos$Number.tubes.raccoon ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Number.tubes.raccoon", p_value = test_result_Number.tubes.raccoon$p.value))

# Variable Number.tubes.chipmunk
test_result_Number.tubes.chipmunk <- wilcox.test(datos$Number.tubes.chipmunk ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Number.tubes.chipmunk", p_value = test_result_Number.tubes.chipmunk$p.value))

# Variable Woodchuck_VisR
test_result_Woodchuck_VisR <- wilcox.test(datos$Woodchuck_VisR ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Woodchuck_VisR", p_value = test_result_Woodchuck_VisR$p.value))

# Variable Deer_VisR
test_result_Deer_VisR <- wilcox.test(datos$Deer_VisR ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Deer_VisR", p_value = test_result_Deer_VisR$p.value))

# Variable Raccon_VisR
test_result_Raccon_VisR <- wilcox.test(datos$Raccon_VisR ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Raccon_VisR", p_value = test_result_Raccon_VisR$p.value))

# Variable Cat_VisR
test_result_Cat_VisR <- wilcox.test(datos$Cat_VisR ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Cat_VisR", p_value = test_result_Cat_VisR$p.value))

# Variable Possum_VisR
test_result_Possum_VisR <- wilcox.test(datos$Possum_VisR ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Possum_VisR", p_value = test_result_Possum_VisR$p.value))


# Variable Skunk_VisR
test_result_Skunk_VisR <- wilcox.test(datos$Skunk_VisR ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Skunk_VisR", p_value = test_result_Skunk_VisR$p.value))


# Variable Squirrel_VisR
test_result_Squirrel_VisR <- wilcox.test(datos$Squirrel_VisR ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Squirrel_VisR", p_value = test_result_Squirrel_VisR$p.value))



# Variable ApproxMOrnamentals
test_result_ApproxMOrnamentals <- wilcox.test(datos$ApproxMOrnamentals ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "ApproxMOrnamentals", p_value = test_result_ApproxMOrnamentals$p.value))

# Variable ApproxMherbaceous
test_result_ApproxMherbaceous <- wilcox.test(datos$ApproxMherbaceous ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "ApproxMherbaceous", p_value = test_result_ApproxMherbaceous$p.value))

# Variable ApproxMnonherbceous
test_result_ApproxMnonherbaceous <- wilcox.test(datos$ApproxMnonherbaceous ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "ApproxMnonherbaceous", p_value = test_result_ApproxMnonherbaceous$p.value))

# Variable ApproxMweeds
test_result_ApproxMweeds <- wilcox.test(datos$ApproxMweeds ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "ApproxMweeds", p_value = test_result_ApproxMweeds$p.value))

# Variable ApproxMgrass
test_result_ApproxMgrass <- wilcox.test(datos$ApproxMgrass ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "ApproxMgrass", p_value = test_result_ApproxMweeds$p.value))


# Variable prop.shrub
test_result_prop.shrub <- wilcox.test(datos$prop.shrub ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "prop.shrub", p_value = test_result_prop.shrub$p.value))

# Variable prop.lowcan
test_result_prop.lowcan <- wilcox.test(datos$prop.lowcan ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "prop.lowcan", p_value = test_result_prop.lowcan$p.value))

# Variable prop.highcan
test_result_prop.highcan <- wilcox.test(datos$prop.highcan ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "prop.highcan", p_value = test_result_prop.highcan$p.value))

# Variable prop.bare
test_result_prop.bare <- wilcox.test(datos$prop.bare ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "prop.bare", p_value = test_result_prop.bare$p.value))

# Variable prop.imperv
test_result_prop.imperv <- wilcox.test(datos$prop.imperv ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "prop.imperv", p_value = test_result_prop.imperv$p.value))


# Variable prop.grass
test_result_prop.grass <- wilcox.test(datos$prop.grass ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "prop.grass", p_value = test_result_prop.grass$p.value))

# Variable prop.shrub
test_result_prop.shrub <- wilcox.test(datos$prop.shrub ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "prop.shrub", p_value = test_result_prop.shrub$p.value))

# Variable prop.lowcan
test_result_prop.lowcan <- wilcox.test(datos$prop.lowcan ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "prop.lowcan", p_value = test_result_prop.lowcan$p.value))

# Variable prop.highcan
test_result_prop.highcan <- wilcox.test(datos$prop.highcan ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "prop.highcan", p_value = test_result_prop.highcan$p.value))

# Variable prop.bare
test_result_prop.bare <- wilcox.test(datos$prop.bare ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "prop.bare", p_value = test_result_prop.bare$p.value))

# Variable prop.imperv
test_result_prop.imperv <- wilcox.test(datos$prop.imperv ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "prop.imperv", p_value = test_result_prop.imperv$p.value))

# Variable Acres
test_result_Acres <- wilcox.test(datos$Acres ~ datos$Ticks_label)
results <- rbind(results, data.frame(Variable = "Acres", p_value = test_result_Acres$p.value))

# Procesa los resultados para incluir significancia
results <- results %>%
  mutate(Significance = case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ ""
  ))

# Formatea los p-valores a cuatro decimales
results$p_value <- formatC(results$p_value, format = "f", digits = 4)

# Formatea la tabla para un documento Word
results %>%
  kable("html", col.names = c("Variable", "p_value", "Significance"), align = "c") %>%
  kable_styling(full_width = FALSE, position = "left", bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, color = "black") %>%
  column_spec(2, color = "black") %>%
  column_spec(3, bold = TRUE, color = "red") %>%
  row_spec(which(results$Significance != ""), bold = TRUE) %>%
  row_spec(0, bold = TRUE, color = "black")
```

# Hipótesis y análisis univariados:

## Deer-Fencing

```{R deer}
kruskal.test(datos$Fencing.yard., datos$Deer_VisR)
```

## Animales-ApproxM...

```{R animal}
# Extract numeric variables related to animals
animal_ApproxM_vars <- c("Woodchuck_VisR", "Deer_VisR",	"Raccon_VisR",	"Cat_VisR",	"Possum_VisR",	"Skunk_VisR", "Squirrel_VisR", "ApproxMOrnamentals",	"ApproxMherbaceous", "ApproxMnonherbaceous", "ApproxMweeds", "ApproxMevergreen", "ApproxMgrass")
  
  # Compute the Spearman correlation matrix with significance
  library(Hmisc)
  cor_res <- rcorr(as.matrix(datos[animal_ApproxM_vars]), type = "spearman")
  
  # Extract the correlation coefficients and p-values
  cor_matrix <- cor_res$r
  p_matrix <- cor_res$P
  
  # Set the diagonal elements of both matrices to NA
  diag(cor_matrix) <- NA
  diag(p_matrix) <- NA
  
  # Format the matrices with three decimal places and no scientific notation
  formatted_cor_matrix <- formatC(cor_matrix, format = "f", digits = 3)
  formatted_p_matrix <- formatC(p_matrix, format = "f", digits = 3)
  
    # Convert matrices to data frames for better kable formatting
  cor_df <- as.data.frame(formatted_cor_matrix)
  p_df <- as.data.frame(formatted_p_matrix)
  
  # Create row and column names for clarity
  rownames(cor_df) <- colnames(cor_df) <- animal_ApproxM_vars
  rownames(p_df) <- colnames(p_df) <- animal_ApproxM_vars
  
  # Print the correlation matrix using kable
  kable(cor_df, caption = "Spearman Correlation Matrix", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
        column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)
  
  # Print the p-value matrix using kable
  kable(p_df, caption = "P-Value Matrix for Spearman Correlations", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
    column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)        
  

  # Visualize the correlation matrix without the diagonal elements
  corrplot(cor_matrix, method = "circle", na.label = " ")
  # Print the p-value matrix using kable
  kable(p_df, caption = "P-Value Matrix for Spearman Correlations", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
    column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)   
```

##Animales-Prop

```{R animal}
# Extract numeric variables related to animals
animal_ApproxM_vars2 <- c("Woodchuck_VisR", "Deer_VisR",	"Raccon_VisR",	"Cat_VisR",	"Possum_VisR",	"Skunk_VisR", "Squirrel_VisR", "prop.shrub", "prop.lowcan", "prop.highcan", "prop.bare", "prop.imperv", "prop.grass")
  
  # Compute the Spearman correlation matrix with significance
  library(Hmisc)
  cor_res <- rcorr(as.matrix(datos[animal_ApproxM_vars2]), type = "spearman")
  
  # Extract the correlation coefficients and p-values
  cor_matrix <- cor_res$r
  p_matrix <- cor_res$P
  
  # Set the diagonal elements of both matrices to NA
  diag(cor_matrix) <- NA
  diag(p_matrix) <- NA
  
  # Format the matrices with three decimal places and no scientific notation
  formatted_cor_matrix <- formatC(cor_matrix, format = "f", digits = 3)
  formatted_p_matrix <- formatC(p_matrix, format = "f", digits = 3)
  
    # Convert matrices to data frames for better kable formatting
  cor_df <- as.data.frame(formatted_cor_matrix)
  p_df <- as.data.frame(formatted_p_matrix)
  
  # Create row and column names for clarity
  rownames(cor_df) <- colnames(cor_df) <- animal_ApproxM_vars2
  rownames(p_df) <- colnames(p_df) <- animal_ApproxM_vars2
  
  # Print the correlation matrix using kable
  kable(cor_df, caption = "Spearman Correlation Matrix", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
        column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)
  
  # Print the p-value matrix using kable
  kable(p_df, caption = "P-Value Matrix for Spearman Correlations", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
    column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)        
  

  # Visualize the correlation matrix without the diagonal elements
  corrplot(cor_matrix, method = "circle", na.label = " ")
  # Print the p-value matrix using kable
  kable(p_df, caption = "P-Value Matrix for Spearman Correlations", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
    column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)   
```

## Animales-Nº tubes

```{R tubes}
 # Extract numeric variables related to animals
  Animals_tubes_vars <- c("Deer_VisR", "Raccon_VisR", "Woodchuck_VisR", 
         "Cat_VisR", "Possum_VisR", "Skunk_VisR", "Squirrel_VisR", "Number.tubes","Number.tubes.with.hair", "Number.tubes.peromyscus",	"Number.tubes.insectivore","Number.tubes.vole", "Number.tubes.raccoon", "Number.tubes.chipmunk")
  
  # Compute the Spearman correlation matrix with significance
  library(Hmisc)
  cor_res <- rcorr(as.matrix(datos[Animals_tubes_vars]), type = "spearman")
  
  # Extract the correlation coefficients and p-values
  cor_matrix <- cor_res$r
  p_matrix <- cor_res$P
  
  # Set the diagonal elements of both matrices to NA
  diag(cor_matrix) <- NA
  diag(p_matrix) <- NA
  
  # Format the matrices with three decimal places and no scientific notation
  formatted_cor_matrix <- formatC(cor_matrix, format = "f", digits = 3)
  formatted_p_matrix <- formatC(p_matrix, format = "f", digits = 3)
  
    # Convert matrices to data frames for better kable formatting
  cor_df <- as.data.frame(formatted_cor_matrix)
  p_df <- as.data.frame(formatted_p_matrix)
  
  # Create row and column names for clarity
  rownames(cor_df) <- colnames(cor_df) <- Animals_tubes_vars
  rownames(p_df) <- colnames(p_df) <- Animals_tubes_vars
  
  # Print the correlation matrix using kable
  kable(cor_df, caption = "Spearman Correlation Matrix", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
        column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)
  
  # Print the p-value matrix using kable
  kable(p_df, caption = "P-Value Matrix for Spearman Correlations", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
    column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)        
  

  # Visualize the correlation matrix without the diagonal elements
  corrplot(cor_matrix, method = "circle", na.label = " ")
```

##Animales-Log.brush/Food.shelter/Lawn/Vegetable/Birdfeeder/Trashcan/Compost.bin/Wood

```{R  Animales-trash}
# Variable Woodchuck

results <- data.frame(Variable = character(), p_value = numeric(), stringsAsFactors = FALSE)
test_result_log.brush <- wilcox.test(datos$Woodchuck_VisR ~ datos$Log.brush, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Woodchuck-Log.brush", p_value = test_result_log.brush$p.value))


test_result_Food.shelter <- wilcox.test(datos$Woodchuck_VisR ~ datos$Food.shelter, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Woodchuck-Food.shelter", p_value = test_result_Food.shelter$p.value))

test_result_Lawn <- wilcox.test(datos$Woodchuck_VisR ~ datos$Lawn, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Woodchuck-Lawn", p_value = test_result_log.brush$p.value))

test_result_Vegetable <- wilcox.test(datos$Woodchuck_VisR ~ datos$Vegetable, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Woodchuck-Vegetable", p_value = test_result_Vegetable$p.value))

test_result_Birdfeeder <- wilcox.test(datos$Woodchuck_VisR ~ datos$Birdfeeder, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Woodchuck-Birdfeeder", p_value = test_result_Birdfeeder$p.value))

test_result_Trashcan <- wilcox.test(datos$Woodchuck_VisR ~ datos$Trashcan, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Woodchuck-Trashcan", p_value = test_result_Trashcan$p.value))

test_result_Compost.bin <- wilcox.test(datos$Woodchuck_VisR ~ datos$Compost.bin, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Woodchuck-Compost.bin", p_value = test_result_Compost.bin$p.value))

test_result_Wood <- wilcox.test(datos$Woodchuck_VisR ~ datos$Wood, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Woodchuck-Trashcan", p_value = test_result_Wood$p.value))

# Variable Deer

test_result_log.brush <- wilcox.test(datos$Deer_VisR ~ datos$Log.brush, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Deer_VisR-Log.brush", p_value = test_result_log.brush$p.value))


test_result_Food.shelter <- wilcox.test(datos$Deer_VisR ~ datos$Food.shelter, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Deer_VisR-Food.shelter", p_value = test_result_Food.shelter$p.value))

test_result_Lawn <- wilcox.test(datos$Deer_VisR ~ datos$Lawn, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Deer_VisR-Lawn", p_value = test_result_log.brush$p.value))

test_result_Vegetable <- wilcox.test(datos$Deer_VisR ~ datos$Vegetable, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Deer_VisR-Vegetable", p_value = test_result_Vegetable$p.value))

test_result_Birdfeeder <- wilcox.test(datos$Deer_VisR ~ datos$Birdfeeder, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Deer_VisR-Birdfeeder", p_value = test_result_Birdfeeder$p.value))

test_result_Trashcan <- wilcox.test(datos$Deer_VisR ~ datos$Trashcan, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Deer_VisR-Trashcan", p_value = test_result_Trashcan$p.value))

test_result_Compost.bin <- wilcox.test(datos$Deer_VisR ~ datos$Compost.bin, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Deer_VisR-Compost.bin", p_value = test_result_Compost.bin$p.value))

test_result_Wood <- wilcox.test(datos$Deer_VisR ~ datos$Wood, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Deer_VisR-Trashcan", p_value = test_result_Wood$p.value))

# Variable Raccon

test_result_log.brush <- wilcox.test(datos$Raccon_VisR ~ datos$Log.brush, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Raccon_VisR-Log.brush", p_value = test_result_log.brush$p.value))


test_result_Food.shelter <- wilcox.test(datos$Raccon_VisR ~ datos$Food.shelter, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Raccon_VisR-Food.shelter", p_value = test_result_Food.shelter$p.value))

test_result_Lawn <- wilcox.test(datos$Raccon_VisR ~ datos$Lawn, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Raccon_VisR-Lawn", p_value = test_result_log.brush$p.value))

test_result_Vegetable <- wilcox.test(datos$Raccon_VisR ~ datos$Vegetable, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Raccon_VisR-Vegetable", p_value = test_result_Vegetable$p.value))

test_result_Birdfeeder <- wilcox.test(datos$Raccon_VisR ~ datos$Birdfeeder, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Raccon_VisR-Birdfeeder", p_value = test_result_Birdfeeder$p.value))

test_result_Trashcan <- wilcox.test(datos$Raccon_VisR ~ datos$Trashcan, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Raccon_VisR-Trashcan", p_value = test_result_Trashcan$p.value))

test_result_Compost.bin <- wilcox.test(datos$Raccon_VisR ~ datos$Compost.bin, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Raccon_VisR-Compost.bin", p_value = test_result_Compost.bin$p.value))

test_result_Wood <- wilcox.test(datos$Raccon_VisR ~ datos$Wood, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Raccon_VisR-Trashcan", p_value = test_result_Wood$p.value))

# Variable Cat

test_result_log.brush <- wilcox.test(datos$Cat_VisR ~ datos$Log.brush, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Cat_VisR-Log.brush", p_value = test_result_log.brush$p.value))


test_result_Food.shelter <- wilcox.test(datos$Cat_VisR ~ datos$Food.shelter, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Cat_VisR-Food.shelter", p_value = test_result_Food.shelter$p.value))

test_result_Lawn <- wilcox.test(datos$Cat_VisR ~ datos$Lawn, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Cat_VisR-Lawn", p_value = test_result_log.brush$p.value))

test_result_Vegetable <- wilcox.test(datos$Cat_VisR ~ datos$Vegetable, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Cat_VisR-Vegetable", p_value = test_result_Vegetable$p.value))

test_result_Birdfeeder <- wilcox.test(datos$Cat_VisR ~ datos$Birdfeeder, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Cat_VisR-Birdfeeder", p_value = test_result_Birdfeeder$p.value))

test_result_Trashcan <- wilcox.test(datos$Cat_VisR ~ datos$Trashcan, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Cat_VisR-Trashcan", p_value = test_result_Trashcan$p.value))

test_result_Compost.bin <- wilcox.test(datos$Cat_VisR ~ datos$Compost.bin, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Cat_VisR-Compost.bin", p_value = test_result_Compost.bin$p.value))

test_result_Wood <- wilcox.test(datos$Cat_VisR ~ datos$Wood, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Cat_VisR-Trashcan", p_value = test_result_Wood$p.value))

# Variable Possum

test_result_log.brush <- wilcox.test(datos$Possum_VisR ~ datos$Log.brush, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Possum_VisR-Log.brush", p_value = test_result_log.brush$p.value))


test_result_Food.shelter <- wilcox.test(datos$Possum_VisR ~ datos$Food.shelter, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Possum_VisR-Food.shelter", p_value = test_result_Food.shelter$p.value))

test_result_Lawn <- wilcox.test(datos$Possum_VisR ~ datos$Lawn, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Possum_VisR-Lawn", p_value = test_result_log.brush$p.value))

test_result_Vegetable <- wilcox.test(datos$Possum_VisR ~ datos$Vegetable, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Possum_VisR-Vegetable", p_value = test_result_Vegetable$p.value))

test_result_Birdfeeder <- wilcox.test(datos$Possum_VisR ~ datos$Birdfeeder, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Possum_VisR-Birdfeeder", p_value = test_result_Birdfeeder$p.value))

test_result_Trashcan <- wilcox.test(datos$Possum_VisR ~ datos$Trashcan, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Possum_VisR-Trashcan", p_value = test_result_Trashcan$p.value))

test_result_Compost.bin <- wilcox.test(datos$Possum_VisR ~ datos$Compost.bin, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Possum_VisR-Compost.bin", p_value = test_result_Compost.bin$p.value))

test_result_Wood <- wilcox.test(datos$Possum_VisR ~ datos$Wood, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Possum_VisR-Trashcan", p_value = test_result_Wood$p.value))

# Variable Skunk

test_result_log.brush <- wilcox.test(datos$Skunk_VisR ~ datos$Log.brush, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Skunk_VisR-Log.brush", p_value = test_result_log.brush$p.value))


test_result_Food.shelter <- wilcox.test(datos$Skunk_VisR ~ datos$Food.shelter, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Skunk_VisR-Food.shelter", p_value = test_result_Food.shelter$p.value))

test_result_Lawn <- wilcox.test(datos$Skunk_VisR ~ datos$Lawn, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Skunk_VisR-Lawn", p_value = test_result_log.brush$p.value))

test_result_Vegetable <- wilcox.test(datos$Skunk_VisR ~ datos$Vegetable, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Skunk_VisR-Vegetable", p_value = test_result_Vegetable$p.value))

test_result_Birdfeeder <- wilcox.test(datos$Skunk_VisR ~ datos$Birdfeeder, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Skunk_VisR-Birdfeeder", p_value = test_result_Birdfeeder$p.value))

test_result_Trashcan <- wilcox.test(datos$Skunk_VisR ~ datos$Trashcan, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Skunk_VisR-Trashcan", p_value = test_result_Trashcan$p.value))

test_result_Compost.bin <- wilcox.test(datos$Skunk_VisR ~ datos$Compost.bin, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Skunk_VisR-Compost.bin", p_value = test_result_Compost.bin$p.value))

test_result_Wood <- wilcox.test(datos$Skunk_VisR ~ datos$Wood, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Skunk_VisR-Trashcan", p_value = test_result_Wood$p.value))

# Variable Squirrel

test_result_log.brush <- wilcox.test(datos$Squirrel_VisR ~ datos$Log.brush, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Squirrel_VisR-Log.brush", p_value = test_result_log.brush$p.value))


test_result_Food.shelter <- wilcox.test(datos$Squirrel_VisR ~ datos$Food.shelter, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Squirrel_VisR-Food.shelter", p_value = test_result_Food.shelter$p.value))

test_result_Lawn <- wilcox.test(datos$Squirrel_VisR ~ datos$Lawn, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Squirrel_VisR-Lawn", p_value = test_result_log.brush$p.value))

test_result_Vegetable <- wilcox.test(datos$Squirrel_VisR ~ datos$Vegetable, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Squirrel_VisR-Vegetable", p_value = test_result_Vegetable$p.value))

test_result_Birdfeeder <- wilcox.test(datos$Squirrel_VisR ~ datos$Birdfeeder, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Squirrel_VisR-Birdfeeder", p_value = test_result_Birdfeeder$p.value))

test_result_Trashcan <- wilcox.test(datos$Squirrel_VisR ~ datos$Trashcan, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Squirrel_VisR-Trashcan", p_value = test_result_Trashcan$p.value))

test_result_Compost.bin <- wilcox.test(datos$Squirrel_VisR ~ datos$Compost.bin, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Squirrel_VisR-Compost.bin", p_value = test_result_Compost.bin$p.value))

test_result_Wood <- wilcox.test(datos$Squirrel_VisR ~ datos$Wood, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Squirrel_VisR-Trashcan", p_value = test_result_Wood$p.value))


# Procesa los resultados para incluir significancia
results <- results %>%
  mutate(Significance = case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ ""
  ))

# Formatea los p-valores a cuatro decimales
results$p_value <- formatC(results$p_value, format = "f", digits = 4)

# Formatea la tabla para un documento Word
results %>%
  kable("html", col.names = c("Variable", "p_value", "Significance"), align = "c") %>%
  kable_styling(full_width = FALSE, position = "left", bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, color = "black") %>%
  column_spec(2, color = "black") %>%
  column_spec(3, bold = TRUE, color = "red") %>%
  row_spec(which(results$Significance != ""), bold = TRUE) %>%
  row_spec(0, bold = TRUE, color = "black")




```

##Animals-Type_edge

```{R edge}
kruskal.test(datos$type_edge, datos$Deer_VisR)
kruskal.test(datos$type_edge, datos$Skunk_VisR)
kruskal.test(datos$type_edge, datos$Raccon_VisR)
kruskal.test(datos$type_edge, datos$Possum_VisR)
kruskal.test(datos$type_edge, datos$Cat_VisR)
kruskal.test(datos$type_edge, datos$Squirrel_VisR)
kruskal.test(datos$type_edge, datos$Woodchuck_VisR)


#No entiendo este código que me ha escrito chat gpt para estas variables:
# Ejecutar las pruebas de Kruskal-Wallis
kruskal_deer <- kruskal.test(datos$type_edge, datos$Deer_VisR)$p.value
kruskal_skunk <- kruskal.test(datos$type_edge, datos$Skunk_VisR)$p.value
kruskal_raccon <- kruskal.test(datos$type_edge, datos$Raccon_VisR)$p.value
kruskal_possum <- kruskal.test(datos$type_edge, datos$Possum_VisR)$p.value
kruskal_cat <- kruskal.test(datos$type_edge, datos$Cat_VisR)$p.value
kruskal_squirrel <- kruskal.test(datos$type_edge, datos$Squirrel_VisR)$p.value
kruskal_woodchuck <- kruskal.test(datos$type_edge, datos$Woodchuck_VisR)$p.value



# Crear la tabla con los resultados
p_values_table <- data.frame(
  Comparacion = c("type_edge vs Deer_VisR", "type_edge vs Skunk_VisR", 
                  "type_edge vs Raccon_VisR", "type_edge vs Possum_VisR",
                  "type_edge vs Cat_VisR", "type_edge vs Squirrel_VisR", 
                  "type_edge vs Woodchuck_VisR"),
  P_valor = c(kruskal_deer, kruskal_skunk, kruskal_raccon, kruskal_possum, 
              kruskal_cat, kruskal_squirrel, kruskal_woodchuck)
)

# Imprimir la tabla
print(p_values_table)
```

##Animal- Play/seating

```{R seating}
# Variable Deer
results <- data.frame(Variable = character(), p_value = numeric(), stringsAsFactors = FALSE)

##Play
datos$Play<-as.factor(datos$Play)
test_result_Deer1 <- wilcox.test(datos$Deer_VisR ~ datos$Play)
results <- rbind(results, data.frame(Variable = "Deer_VisR-Play", p_value = test_result_Deer1$p.value))

##Seating
test_result_Deer2 <- wilcox.test(datos$Deer_VisR ~ datos$Seating)
results <- rbind(results, data.frame(Variable = "Deer_VisR-Seating", p_value = test_result_Deer2$p.value))

# Variable Raccoon
##Play
test_result_Raccon1 <- wilcox.test(datos$Raccon_VisR ~ datos$Play)
results <- rbind(results, data.frame(Variable = "Raccon_VisR-Play", p_value = test_result_Raccon1$p.value))

##Seating
test_result_Raccon2 <- wilcox.test(datos$Raccon_VisR ~ datos$Seating)
results <- rbind(results, data.frame(Variable = "Raccon_VisR-Seating", p_value = test_result_Raccon2$p.value))

# Variable Woodchuck

##Play
datos$Play<-as.factor(datos$Play)
test_result_Woodchuck1 <- wilcox.test(datos$Woodchuck_VisR ~ datos$Play)
results <- rbind(results, data.frame(Variable = "Woodchuck_VisR-Play", p_value = test_result_Woodchuck1$p.value))

##Seating
test_result_Woodchuck2 <- wilcox.test(datos$Woodchuck_VisR ~ datos$Seating)
results <- rbind(results, data.frame(Variable = "Woodchuck_VisR-Seating", p_value = test_result_Woodchuck2$p.value))

# Variable Cat
##Play
test_result_Cat1 <- wilcox.test(datos$Cat_VisR ~ datos$Play)
results <- rbind(results, data.frame(Variable = "Cat_VisR-Play", p_value = test_result_Cat1$p.value))

##Seating
test_result_Cat2 <- wilcox.test(datos$Cat_VisR ~ datos$Seating)
results <- rbind(results, data.frame(Variable = "Cat_VisR-Seating", p_value = test_result_Cat2$p.value))

# Variable Possum
##Play
datos$Play<-as.factor(datos$Play)
test_result_Possum1 <- wilcox.test(datos$Possum_VisR ~ datos$Play)
results <- rbind(results, data.frame(Variable = "Possum_VisR-Play", p_value = test_result_Possum1$p.value))

##Seating
test_result_Possum2 <- wilcox.test(datos$Possum_VisR ~ datos$Seating)
results <- rbind(results, data.frame(Variable = "Possum_VisR-Seating", p_value = test_result_Possum2$p.value))

# Variable Skunk
##Play
test_result_Skunk1 <- wilcox.test(datos$Skunk_VisR ~ datos$Play)
results <- rbind(results, data.frame(Variable = "Skunk_VisR-Play", p_value = test_result_Raccon1$p.value))

##Seating
test_result_Skunk2 <- wilcox.test(datos$Skunk_VisR ~ datos$Seating)
results <- rbind(results, data.frame(Variable = "Skunk_VisR-Seating", p_value = test_result_Raccon2$p.value))

# Variable Squirrel
##Play
test_result_Squirrel1 <- wilcox.test(datos$Squirrel_VisR ~ datos$Play)
results <- rbind(results, data.frame(Variable = "Squirrel_VisR-Play", p_value = test_result_Squirrel1$p.value))

##Seating
test_result_Squirrel2 <- wilcox.test(datos$Squirrel_VisR ~ datos$Seating)
results <- rbind(results, data.frame(Variable = "Squirrel_VisR-Seating", p_value = test_result_Squirrel2$p.value))
# Procesa los resultados para incluir significancia
results <- results %>%
  mutate(Significance = case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ ""
  ))


# Formatea los p-valores a cuatro decimales
results$p_value <- formatC(results$p_value, format = "f", digits = 4)

# Formatea la tabla para un documento Word
results %>%
  kable("html", col.names = c("Variable", "p_value", "Significance"), align = "c") %>%
  kable_styling(full_width = FALSE, position = "left", bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, color = "black") %>%
  column_spec(2, color = "black") %>%
  column_spec(3, bold = TRUE, color = "red") %>%
  row_spec(which(results$Significance != ""), bold = TRUE) %>%
  row_spec(0, bold = TRUE, color = "black")



```

## ApproxM-Log.brush/ Food shelter/Lawn/ Vegetable/ Birdfeeder/

Trashcan/Compost.bin/Wood ###ApproxM-Log.brush:

```{R  Variable Approx_Log}
Numeric_plants<- c("ApproxMOrnamentals", "ApproxMherbaceous", "ApproxMnonherbaceous", "ApproxMweeds", "ApproxMevergreen", "ApproxMgrass")
Log.brush <-as.factor(datos$Log.brush)
# Initialize an empty data frame to store results
results <- data.frame(Variable = character(),
                      p_value = numeric(),
                      stringsAsFactors = FALSE)

#Perform Mann-Whitney test for each numeric variable 
for (var in Numeric_plants) {
  test_result <- wilcox.test(datos[[var]] ~ datos$Log.brush, data = datos)
  results <- rbind(results, data.frame(Variable = var, p_value = test_result$p.value))
}

# Display the results
results <- results %>%
  mutate(Significance = case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ ""
  ))

# Format p-values to four decimal places
results$p_value <- formatC(results$p_value, format = "f", digits = 4)

# Format the table for Word document
results %>%
  kable("html", col.names = c("Variable", "P-value", "Significance"), align = "c") %>%
  kable_styling(full_width = FALSE, position = "left", bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, color = "black") %>%
  column_spec(2, color = "black") %>%
  column_spec(3, bold = TRUE, color = "red") %>%
  row_spec(which(results$Significance != ""), bold = TRUE) %>%
  row_spec(0, bold = TRUE, color = "black")

create_violin_plot <- function(data, var_num, target_var) {
 
   ggplot(data, aes_string(x = target_var, y = var_num, fill = target_var)) +
    geom_violin(trim = FALSE) +
    geom_jitter(width = 0.2, size = 0.6, alpha = 0.6) +
    labs(y = var_num, fill = target_var, x = target_var) +
    theme_minimal() +
    theme(
      legend.position = "none",
      plot.title = element_text(size = 8),
      axis.title.x = element_text(size = 8),
      axis.title.y = element_text(size = 8),
      axis.text.x = element_text(size = 7),
      axis.text.y = element_text(size = 7)
    ) +
    ggtitle(var_num)
}
num_plots2 <- list()
for (var in Numeric_plants) {
  num_plots2[[var]] <- create_violin_plot(datos, var, as.factor("Log.brush"))
}

# Arrange the plots in a 4x4 grid
grid.arrange(grobs = num_plots2, ncol = 5, nrow = 3)
```

### ApproxM-Food shelter:

```{R food shelter}

Numeric_plants<- c("ApproxMOrnamentals", "ApproxMherbaceous", "ApproxMnonherbaceous", "ApproxMweeds", "ApproxMevergreen", "ApproxMgrass")

# Initialize an empty data frame to store results
results <- data.frame(Variable = character(),
                      p_value = numeric(),
                      stringsAsFactors = FALSE)
# Perform Mann-Whitney test for each numeric variable 
for (var in Numeric_plants) {
  test_result <- wilcox.test(datos[[var]] ~ datos$Food.shelter, data = datos)
  results <- rbind(results, data.frame(Variable = var, p_value = test_result$p.value))
}

# Display the results
results <- results %>%
  mutate(Significance = case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ ""
  ))

# Format p-values to four decimal places
results$p_value <- formatC(results$p_value, format = "f", digits = 4)

# Format the table for Word document
results %>%
  kable("html", col.names = c("Variable", "P-value", "Significance"), align = "c") %>%
  kable_styling(full_width = FALSE, position = "left", bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, color = "black") %>%
  column_spec(2, color = "black") %>%
  column_spec(3, bold = TRUE, color = "red") %>%
  row_spec(which(results$Significance != ""), bold = TRUE) %>%
  row_spec(0, bold = TRUE, color = "black")

```

### ApproxM-Lawn:

```{R Lawn}
                 
Numeric_plants<- c("ApproxMOrnamentals", "ApproxMherbaceous", "ApproxMnonherbaceous", "ApproxMweeds", "ApproxMevergreen", "ApproxMgrass")

# Initialize an empty data frame to store results
results <- data.frame(Variable = character(),
                      p_value = numeric(),
                      stringsAsFactors = FALSE)
# Perform Mann-Whitney test for each numeric variable 
for (var in Numeric_plants) {
  test_result <- wilcox.test(datos[[var]] ~ datos$Lawn, data = datos)
  results <- rbind(results, data.frame(Variable = var, p_value = test_result$p.value))
}

# Display the results
results <- results %>%
  mutate(Significance = case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ ""
  ))

# Format p-values to four decimal places
results$p_value <- formatC(results$p_value, format = "f", digits = 4)

# Format the table for Word document
results %>%
  kable("html", col.names = c("Variable", "P-value", "Significance"), align = "c") %>%
  kable_styling(full_width = FALSE, position = "left", bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, color = "black") %>%
  column_spec(2, color = "black") %>%
  column_spec(3, bold = TRUE, color = "red") %>%
  row_spec(which(results$Significance != ""), bold = TRUE) %>%
  row_spec(0, bold = TRUE, color = "black")

```

### ApproxM-Birdfeeder:

```{R BIRDFEEDER}

Numeric_plants<- c("ApproxMOrnamentals", "ApproxMherbaceous", "ApproxMnonherbaceous", "ApproxMweeds", "ApproxMevergreen", "ApproxMgrass")

# Initialize an empty data frame to store results
results <- data.frame(Variable = character(),
                      p_value = numeric(),
                      stringsAsFactors = FALSE)                 
# Perform Mann-Whitney test for each numeric variable 
for (var in Numeric_plants) {
  test_result <- wilcox.test(datos[[var]] ~ datos$Birdfeeder, data = datos)
  results <- rbind(results, data.frame(Variable = var, p_value = test_result$p.value))
}

# Display the results
results <- results %>%
  mutate(Significance = case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ ""
  ))

# Format p-values to four decimal places
results$p_value <- formatC(results$p_value, format = "f", digits = 4)

# Format the table for Word document
results %>%
  kable("html", col.names = c("Variable", "P-value", "Significance"), align = "c") %>%
  kable_styling(full_width = FALSE, position = "left", bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, color = "black") %>%
  column_spec(2, color = "black") %>%
  column_spec(3, bold = TRUE, color = "red") %>%
  row_spec(which(results$Significance != ""), bold = TRUE) %>%
  row_spec(0, bold = TRUE, color = "black")

```

### ApproxM-Vegetable:

```{R Vegetable}
                 

Numeric_plants<- c("ApproxMOrnamentals", "ApproxMherbaceous", "ApproxMnonherbaceous", "ApproxMweeds", "ApproxMevergreen", "ApproxMgrass")

# Initialize an empty data frame to store results
results <- data.frame(Variable = character(),
                      p_value = numeric(),
                      stringsAsFactors = FALSE)
# Perform Mann-Whitney test for each numeric variable 
for (var in Numeric_plants) {
  test_result <- wilcox.test(datos[[var]] ~ datos$Vegetable, data = datos)
  results <- rbind(results, data.frame(Variable = var, p_value = test_result$p.value))
}

# Display the results
results <- results %>%
  mutate(Significance = case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ ""
  ))

# Format p-values to four decimal places
results$p_value <- formatC(results$p_value, format = "f", digits = 4)

# Format the table for Word document
results %>%
  kable("html", col.names = c("Variable", "P-value", "Significance"), align = "c") %>%
  kable_styling(full_width = FALSE, position = "left", bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, color = "black") %>%
  column_spec(2, color = "black") %>%
  column_spec(3, bold = TRUE, color = "red") %>%
  row_spec(which(results$Significance != ""), bold = TRUE) %>%
  row_spec(0, bold = TRUE, color = "black")

```

### ApproxM-Trashcan:

```{R TRASHCAN}
                 

Numeric_plants<- c("ApproxMOrnamentals", "ApproxMherbaceous", "ApproxMnonherbaceous", "ApproxMweeds", "ApproxMevergreen", "ApproxMgrass")

# Initialize an empty data frame to store results
results <- data.frame(Variable = character(),
                      p_value = numeric(),
                      stringsAsFactors = FALSE)
# Perform Mann-Whitney test for each numeric variable 
for (var in Numeric_plants) {
  test_result <- wilcox.test(datos[[var]] ~ datos$Trashcan, data = datos)
  results <- rbind(results, data.frame(Variable = var, p_value = test_result$p.value))
}

# Display the results
results <- results %>%
  mutate(Significance = case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ ""
  ))

# Format p-values to four decimal places
results$p_value <- formatC(results$p_value, format = "f", digits = 4)

# Format the table for Word document
results %>%
  kable("html", col.names = c("Variable", "P-value", "Significance"), align = "c") %>%
  kable_styling(full_width = FALSE, position = "left", bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, color = "black") %>%
  column_spec(2, color = "black") %>%
  column_spec(3, bold = TRUE, color = "red") %>%
  row_spec(which(results$Significance != ""), bold = TRUE) %>%
  row_spec(0, bold = TRUE, color = "black")

```

### ApproxM-Compost.bin:

```{R COMPOST BIN}

Numeric_plants<- c("ApproxMOrnamentals", "ApproxMherbaceous", "ApproxMnonherbaceous", "ApproxMweeds", "ApproxMevergreen", "ApproxMgrass")

# Initialize an empty data frame to store results
results <- data.frame(Variable = character(),
                      p_value = numeric(),
                      stringsAsFactors = FALSE)
# Perform Mann-Whitney test for each numeric variable 
for (var in Numeric_plants) {
  test_result <- wilcox.test(datos[[var]] ~ datos$Compost.bin, data = datos)
  results <- rbind(results, data.frame(Variable = var, p_value = test_result$p.value))
}

# Display the results
results <- results %>%
  mutate(Significance = case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ ""
  ))

# Format p-values to four decimal places
results$p_value <- formatC(results$p_value, format = "f", digits = 4)

# Format the table for Word document
results %>%
  kable("html", col.names = c("Variable", "P-value", "Significance"), align = "c") %>%
  kable_styling(full_width = FALSE, position = "left", bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, color = "black") %>%
  column_spec(2, color = "black") %>%
  column_spec(3, bold = TRUE, color = "red") %>%
  row_spec(which(results$Significance != ""), bold = TRUE) %>%
  row_spec(0, bold = TRUE, color = "black")

```

### ApproxM-Wood:

```{R WOOD}

Numeric_plants<- c("ApproxMOrnamentals", "ApproxMherbaceous", "ApproxMnonherbaceous", "ApproxMweeds", "ApproxMevergreen", "ApproxMgrass")

# Initialize an empty data frame to store results
results <- data.frame(Variable = character(),
                      p_value = numeric(),
                      stringsAsFactors = FALSE)
# Perform Mann-Whitney test for each numeric variable 
for (var in Numeric_plants) {
  test_result <- wilcox.test(datos[[var]] ~ datos$Wood, data = datos)
  results <- rbind(results, data.frame(Variable = var, p_value = test_result$p.value))
}

# Display the results
results <- results %>%
  mutate(Significance = case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ ""
  ))

# Format p-values to four decimal places
results$p_value <- formatC(results$p_value, format = "f", digits = 4)

# Format the table for Word document
results %>%
  kable("html", col.names = c("Variable", "P-value", "Significance"), align = "c") %>%
  kable_styling(full_width = FALSE, position = "left", bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, color = "black") %>%
  column_spec(2, color = "black") %>%
  column_spec(3, bold = TRUE, color = "red") %>%
  row_spec(which(results$Significance != ""), bold = TRUE) %>%
  row_spec(0, bold = TRUE, color = "black")

```

## ApproxM-Prop.

highcan/Prop.bare/Prop.imperv/Prop.grass/Prop.shrub/Prop.lowcan

```{R props}

 # Extract numeric variables related to animals
  plants_prop_vars <- c("ApproxMOrnamentals", "ApproxMherbaceous", "ApproxMnonherbaceous","ApproxMweeds", "ApproxMevergreen", "ApproxMgrass","prop.shrub", "prop.lowcan", "prop.highcan", "prop.bare", "prop.imperv", "prop.grass")
  
  # Compute the Spearman correlation matrix with significance
  library(Hmisc)
  cor_res <- rcorr(as.matrix(datos[plants_prop_vars]), type = "spearman")
  
  # Extract the correlation coefficients and p-values
  cor_matrix <- cor_res$r
  p_matrix <- cor_res$P
  
  # Set the diagonal elements of both matrices to NA
  diag(cor_matrix) <- NA
  diag(p_matrix) <- NA
  
  # Format the matrices with three decimal places and no scientific notation
  formatted_cor_matrix <- formatC(cor_matrix, format = "f", digits = 3)
  formatted_p_matrix <- formatC(p_matrix, format = "f", digits = 3)
  
    # Convert matrices to data frames for better kable formatting
  cor_df <- as.data.frame(formatted_cor_matrix)
  p_df <- as.data.frame(formatted_p_matrix)
  
  # Create row and column names for clarity
  rownames(cor_df) <- colnames(cor_df) <- plants_prop_vars
  rownames(p_df) <- colnames(p_df) <- plants_prop_vars
  
  # Print the correlation matrix using kable
  kable(cor_df, caption = "Spearman Correlation Matrix", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
        column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)
  
  # Print the p-value matrix using kable
  kable(p_df, caption = "P-Value Matrix for Spearman Correlations", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
    column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)        
  

  # Visualize the correlation matrix without the diagonal elements
  corrplot(cor_matrix, method = "circle", na.label = " ")
```

##Nºtubes-Prop

```{R N_tubes}

# Extract numeric variables related to animals
  Prop_tubes_vars <- c("prop.shrub", "prop.lowcan", "prop.highcan", "prop.bare", "prop.grass", "prop.imperv", "Number.tubes","Number.tubes.with.hair", "Number.tubes.peromyscus",	"Number.tubes.insectivore","Number.tubes.vole", "Number.tubes.raccoon", "Number.tubes.chipmunk")
  
  # Compute the Spearman correlation matrix with significance
  library(Hmisc)
  cor_res <- rcorr(as.matrix(datos[Prop_tubes_vars]), type = "spearman")
  
  # Extract the correlation coefficients and p-values
  cor_matrix <- cor_res$r
  p_matrix <- cor_res$P
  
  # Set the diagonal elements of both matrices to NA
  diag(cor_matrix) <- NA
  diag(p_matrix) <- NA
  
  # Format the matrices with three decimal places and no scientific notation
  formatted_cor_matrix <- formatC(cor_matrix, format = "f", digits = 3)
  formatted_p_matrix <- formatC(p_matrix, format = "f", digits = 3)
  
    # Convert matrices to data frames for better kable formatting
  cor_df <- as.data.frame(formatted_cor_matrix)
  p_df <- as.data.frame(formatted_p_matrix)
  
  # Create row and column names for clarity
  rownames(cor_df) <- colnames(cor_df) <- Prop_tubes_vars
  rownames(p_df) <- colnames(p_df) <- Prop_tubes_vars
  
  # Print the correlation matrix using kable
  kable(cor_df, caption = "Spearman Correlation Matrix", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
        column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)
  
  # Print the p-value matrix using kable
  kable(p_df, caption = "P-Value Matrix for Spearman Correlations", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
    column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)        
  

  # Visualize the correlation matrix without the diagonal elements
  corrplot(cor_matrix, method = "circle", na.label = " ")
```

##Nºtubes-Log.brush

```{R N_tubes}

# Variable Nº tubes

results <- data.frame(Variable = character(), p_value = numeric(), stringsAsFactors = FALSE)
test_result_log.brush <- wilcox.test(datos$Number.tubes ~ datos$Log.brush, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes-Log.brush", p_value = test_result_log.brush$p.value))


test_result_Food.shelter <- wilcox.test(datos$Number.tubes ~ datos$Food.shelter, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes-Food.shelter", p_value = test_result_Food.shelter$p.value))

test_result_Lawn <- wilcox.test(datos$Number.tubes ~ datos$Lawn, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes-Lawn", p_value = test_result_log.brush$p.value))

test_result_Vegetable <- wilcox.test(datos$Number.tubes ~ datos$Vegetable, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes-Vegetable", p_value = test_result_Vegetable$p.value))

test_result_Birdfeeder <- wilcox.test(datos$Number.tubes ~ datos$Birdfeeder, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes-Birdfeeder", p_value = test_result_Birdfeeder$p.value))

test_result_Trashcan <- wilcox.test(datos$Number.tubes ~ datos$Trashcan, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes-Trashcan", p_value = test_result_Trashcan$p.value))

test_result_Compost.bin <- wilcox.test(datos$Woodchuck_VisR ~ datos$Compost.bin, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Woodchuck-Compost.bin", p_value = test_result_Compost.bin$p.value))

test_result_Wood <- wilcox.test(datos$Number.tubes ~ datos$Wood, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes-Trashcan", p_value = test_result_Wood$p.value))

# Variable Number.tubes w/hair

test_result_log.brush <- wilcox.test(datos$Number.tubes.with.hair ~ datos$Log.brush, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.with.hair-Log.brush", p_value = test_result_log.brush$p.value))


test_result_Food.shelter <- wilcox.test(datos$Number.tubes.with.hair ~ datos$Food.shelter, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.with.hair-Food.shelter", p_value = test_result_Food.shelter$p.value))

test_result_Lawn <- wilcox.test(datos$Number.tubes.with.hair ~ datos$Lawn, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.with.hair-Lawn", p_value = test_result_log.brush$p.value))

test_result_Vegetable <- wilcox.test(datos$Deer_VisR ~ datos$Vegetable, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Deer_VisR-Vegetable", p_value = test_result_Vegetable$p.value))

test_result_Birdfeeder <- wilcox.test(datos$Number.tubes.with.hair ~ datos$Birdfeeder, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.with.hair-Birdfeeder", p_value = test_result_Birdfeeder$p.value))

test_result_Trashcan <- wilcox.test(datos$Deer_VisR ~ datos$Trashcan, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Deer_VisR-Trashcan", p_value = test_result_Trashcan$p.value))

test_result_Compost.bin <- wilcox.test(datos$Number.tubes.with.hair ~ datos$Compost.bin, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.with.hair-Compost.bin", p_value = test_result_Compost.bin$p.value))

test_result_Wood <- wilcox.test(datos$Number.tubes.with.hair ~ datos$Wood, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.with.hair-Trashcan", p_value = test_result_Wood$p.value))

# Variable Number. tubes. raccoon

test_result_log.brush <- wilcox.test(datos$Number.tubes.raccoon ~ datos$Log.brush, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.raccoon-Log.brush", p_value = test_result_log.brush$p.value))


test_result_Food.shelter <- wilcox.test(datos$Number.tubes.raccoon ~ datos$Food.shelter, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.raccoon-Food.shelter", p_value = test_result_Food.shelter$p.value))

test_result_Lawn <- wilcox.test(datos$Number.tubes.raccoon ~ datos$Lawn, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.raccoon-Lawn", p_value = test_result_log.brush$p.value))

test_result_Vegetable <- wilcox.test(datos$Number.tubes.raccoon ~ datos$Vegetable, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.raccoon-Vegetable", p_value = test_result_Vegetable$p.value))

test_result_Birdfeeder <- wilcox.test(datos$Number.tubes.raccoon ~ datos$Birdfeeder, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.raccoon-Birdfeeder", p_value = test_result_Birdfeeder$p.value))

test_result_Trashcan <- wilcox.test(datos$Number.tubes.raccoon ~ datos$Trashcan, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.raccoon-Trashcan", p_value = test_result_Trashcan$p.value))

test_result_Compost.bin <- wilcox.test(datos$Number.tubes.raccoon ~ datos$Compost.bin, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.raccoon-Compost.bin", p_value = test_result_Compost.bin$p.value))

test_result_Wood <- wilcox.test(datos$Number.tubes.raccoon ~ datos$Wood, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.raccoon-Trashcan", p_value = test_result_Wood$p.value))

# Variable Number tubes chipmunk

test_result_log.brush <- wilcox.test(datos$Number.tubes.chipmunk ~ datos$Log.brush, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Cat_VisR-Log.brush", p_value = test_result_log.brush$p.value))


test_result_Food.shelter <- wilcox.test(datos$Number.tubes.chipmunk ~ datos$Food.shelter, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.chipmunk-Food.shelter", p_value = test_result_Food.shelter$p.value))

test_result_Lawn <- wilcox.test(datos$Number.tubes.chipmunk ~ datos$Lawn, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.chipmunk-Lawn", p_value = test_result_log.brush$p.value))

test_result_Vegetable <- wilcox.test(datos$Number.tubes.chipmunk ~ datos$Vegetable, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.chipmunk-Vegetable", p_value = test_result_Vegetable$p.value))

test_result_Birdfeeder <- wilcox.test(datos$Cat_VisR ~ datos$Birdfeeder, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Cat_VisR-Birdfeeder", p_value = test_result_Birdfeeder$p.value))

test_result_Trashcan <- wilcox.test(datos$Number.tubes.chipmunk ~ datos$Trashcan, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.chipmunk-Trashcan", p_value = test_result_Trashcan$p.value))

test_result_Compost.bin <- wilcox.test(datos$Number.tubes.chipmunk ~ datos$Compost.bin, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.chipmunk-Compost.bin", p_value = test_result_Compost.bin$p.value))

test_result_Wood <- wilcox.test(datos$Number.tubes.chipmunk ~ datos$Wood, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.chipmunk-Trashcan", p_value = test_result_Wood$p.value))

# Variable Number tubes insectivore

test_result_log.brush <- wilcox.test(datos$Number.tubes.insectivore ~ datos$Log.brush, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.insectivore-Log.brush", p_value = test_result_log.brush$p.value))


test_result_Food.shelter <- wilcox.test(datos$Number.tubes.insectivore ~ datos$Food.shelter, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.insectivore-Food.shelter", p_value = test_result_Food.shelter$p.value))

test_result_Lawn <- wilcox.test(datos$Number.tubes.insectivore ~ datos$Lawn, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.insectivore-Lawn", p_value = test_result_log.brush$p.value))

test_result_Vegetable <- wilcox.test(datos$Number.tubes.insectivore ~ datos$Vegetable, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.insectivore-Vegetable", p_value = test_result_Vegetable$p.value))

test_result_Birdfeeder <- wilcox.test(datos$Number.tubes.insectivore ~ datos$Birdfeeder, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.insectivore-Birdfeeder", p_value = test_result_Birdfeeder$p.value))

test_result_Trashcan <- wilcox.test(datos$Number.tubes.insectivore ~ datos$Trashcan, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.insectivore-Trashcan", p_value = test_result_Trashcan$p.value))

test_result_Compost.bin <- wilcox.test(datos$Number.tubes.insectivore ~ datos$Compost.bin, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.insectivore-Compost.bin", p_value = test_result_Compost.bin$p.value))

test_result_Wood <- wilcox.test(datos$Possum_VisR ~ datos$Wood, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Possum_VisR-Trashcan", p_value = test_result_Wood$p.value))

# Variable Number tubes vole

test_result_log.brush <- wilcox.test(datos$Number.tubes.vole ~ datos$Log.brush, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.vole-Log.brush", p_value = test_result_log.brush$p.value))


test_result_Food.shelter <- wilcox.test(datos$Number.tubes.vole ~ datos$Food.shelter, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.vole-Food.shelter", p_value = test_result_Food.shelter$p.value))

test_result_Lawn <- wilcox.test(datos$Number.tubes.vole ~ datos$Lawn, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.vole-Lawn", p_value = test_result_log.brush$p.value))

test_result_Vegetable <- wilcox.test(datos$Number.tubes.vole ~ datos$Vegetable, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.vole-Vegetable", p_value = test_result_Vegetable$p.value))

test_result_Birdfeeder <- wilcox.test(datos$Number.tubes.vole ~ datos$Birdfeeder, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.vole-Birdfeeder", p_value = test_result_Birdfeeder$p.value))

test_result_Trashcan <- wilcox.test(datos$Number.tubes.vole ~ datos$Trashcan, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.vole-Trashcan", p_value = test_result_Trashcan$p.value))

test_result_Compost.bin <- wilcox.test(datos$Number.tubes.vole ~ datos$Compost.bin, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.vole-Compost.bin", p_value = test_result_Compost.bin$p.value))

test_result_Wood <- wilcox.test(datos$Number.tubes.vole ~ datos$Wood, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.vole-Trashcan", p_value = test_result_Wood$p.value))

# Variable Number tubes peromyscus

test_result_log.brush <- wilcox.test(datos$Number.tubes.peromyscus ~ datos$Log.brush, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.peromyscus-Log.brush", p_value = test_result_log.brush$p.value))


test_result_Food.shelter <- wilcox.test(datos$Number.tubes.peromyscus ~ datos$Food.shelter, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.peromyscus-Food.shelter", p_value = test_result_Food.shelter$p.value))

test_result_Lawn <- wilcox.test(datos$Number.tubes.peromyscus ~ datos$Lawn, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.peromyscus-Lawn", p_value = test_result_log.brush$p.value))

test_result_Vegetable <- wilcox.test(datos$Number.tubes.peromyscus ~ datos$Vegetable, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.peromyscus-Vegetable", p_value = test_result_Vegetable$p.value))

test_result_Birdfeeder <- wilcox.test(datos$Number.tubes.peromyscus ~ datos$Birdfeeder, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.peromyscus-Birdfeeder", p_value = test_result_Birdfeeder$p.value))

test_result_Trashcan <- wilcox.test(datos$Number.tubes.peromyscus ~ datos$Trashcan, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.peromyscus-Trashcan", p_value = test_result_Trashcan$p.value))

test_result_Compost.bin <- wilcox.test(datos$Number.tubes.peromyscus ~ datos$Compost.bin, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.peromyscus-Compost.bin", p_value = test_result_Compost.bin$p.value))

test_result_Wood <- wilcox.test(datos$Number.tubes.peromyscus ~ datos$Wood, exact=FALSE)
results <- rbind(results, data.frame(Variable = "Number.tubes.peromyscus-Trashcan", p_value = test_result_Wood$p.value))
# Procesa los resultados para incluir significancia
results <- results %>%
  mutate(Significance = case_when(
    p_value < 0.001 ~ "***",
    p_value < 0.01 ~ "**",
    p_value < 0.05 ~ "*",
    TRUE ~ ""
  ))

# Formatea los p-valores a cuatro decimales
results$p_value <- formatC(results$p_value, format = "f", digits = 4)

# Formatea la tabla para un documento Word
results %>%
  kable("html", col.names = c("Variable", "p_value", "Significance"), align = "c") %>%
  kable_styling(full_width = FALSE, position = "left", bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, color = "black") %>%
  column_spec(2, color = "black") %>%
  column_spec(3, bold = TRUE, color = "red") %>%
  row_spec(which(results$Significance != ""), bold = TRUE) %>%
  row_spec(0, bold = TRUE, color = "black")




```

## Nºtubes-ApproxM...

```{R animal}
# Extract numeric variables related to animals
animal_ApproxM_vars <- c("Number.tubes","Number.tubes.with.hair", "Number.tubes.peromyscus",	"Number.tubes.insectivore","Number.tubes.vole", "Number.tubes.raccoon", "Number.tubes.chipmunk", "ApproxMOrnamentals",	"ApproxMherbaceous", "ApproxMnonherbaceous", "ApproxMweeds", "ApproxMevergreen", "ApproxMgrass")
  
  # Compute the Spearman correlation matrix with significance
  library(Hmisc)
  cor_res <- rcorr(as.matrix(datos[animal_ApproxM_vars]), type = "spearman")
  
  # Extract the correlation coefficients and p-values
  cor_matrix <- cor_res$r
  p_matrix <- cor_res$P
  
  # Set the diagonal elements of both matrices to NA
  diag(cor_matrix) <- NA
  diag(p_matrix) <- NA
  
  # Format the matrices with three decimal places and no scientific notation
  formatted_cor_matrix <- formatC(cor_matrix, format = "f", digits = 3)
  formatted_p_matrix <- formatC(p_matrix, format = "f", digits = 3)
  
    # Convert matrices to data frames for better kable formatting
  cor_df <- as.data.frame(formatted_cor_matrix)
  p_df <- as.data.frame(formatted_p_matrix)
  
  # Create row and column names for clarity
  rownames(cor_df) <- colnames(cor_df) <- animal_ApproxM_vars
  rownames(p_df) <- colnames(p_df) <- animal_ApproxM_vars
  
  # Print the correlation matrix using kable
  kable(cor_df, caption = "Spearman Correlation Matrix", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
        column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)
  
  # Print the p-value matrix using kable
  kable(p_df, caption = "P-Value Matrix for Spearman Correlations", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
    column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)        
  

  # Visualize the correlation matrix without the diagonal elements
  corrplot(cor_matrix, method = "circle", na.label = " ")
  # Print the p-value matrix using kable
  kable(p_df, caption = "P-Value Matrix for Spearman Correlations", align = "c") %>%
    kable_styling(full_width = FALSE, position = "left", 
                  bootstrap_options = c("striped", "hover", "condensed")) %>%
    column_spec(1:ncol(cor_df), color = "black") %>%  
    row_spec(0, color = "black", bold = TRUE)   
```

##Nº tubes-Type_edge

```{R edge}
kruskal.test(datos$Number.tubes, datos$Deer_VisR)
kruskal.test(datos$Number.tubes.with.hair, datos$Skunk_VisR)
kruskal.test(datos$Number.tubes.peromyscus, datos$Raccon_VisR)
kruskal.test(datos$Number.tubes.vole, datos$Possum_VisR)
kruskal.test(datos$Number.tubes.raccoon, datos$Cat_VisR)
kruskal.test(datos$Number.tubes.chipmunk, datos$Squirrel_VisR)


#No entiendo este código que me ha escrito chat gpt para estas variables:
# Ejecutar las pruebas de Kruskal-Wallis
kruskal_deer <- kruskal.test(datos$type_edge, datos$Deer_VisR)$p.value
kruskal_skunk <- kruskal.test(datos$type_edge, datos$Skunk_VisR)$p.value
kruskal_raccon <- kruskal.test(datos$type_edge, datos$Raccon_VisR)$p.value
kruskal_possum <- kruskal.test(datos$type_edge, datos$Possum_VisR)$p.value
kruskal_cat <- kruskal.test(datos$type_edge, datos$Cat_VisR)$p.value
kruskal_squirrel <- kruskal.test(datos$type_edge, datos$Squirrel_VisR)$p.value
kruskal_woodchuck <- kruskal.test(datos$type_edge, datos$Woodchuck_VisR)$p.value



# Crear la tabla con los resultados
p_values_table <- data.frame(
  Comparacion = c("type_edge vs Deer_VisR", "type_edge vs Skunk_VisR", 
                  "type_edge vs Raccon_VisR", "type_edge vs Possum_VisR",
                  "type_edge vs Cat_VisR", "type_edge vs Squirrel_VisR", 
                  "type_edge vs Woodchuck_VisR"),
  P_valor = c(kruskal_deer, kruskal_skunk, kruskal_raccon, kruskal_possum, 
              kruskal_cat, kruskal_squirrel, kruskal_woodchuck)
)

# Imprimir la tabla
print(p_values_table)
```

#Interpretación de resultados:

0.- La presencia de tick está relacionada positivamente con la presencia
de animales pero también con la presencia de maleza (weeds) y de
peromyscus.

1.- La presencia de maleza (weeds) es mayor cuanto más hierba haya
(grass) y menos cuanto más highcan haya.

2.- A más proporción de lowcan menos plantas herbáceas hay.

3.- Cuanta menos hierba (grass), mayor cantidad de plantas ornamentales
hay.

4.- La presencia de cats, raccoons y woodchucks es menor si hay hierba
(weeds).

5.- A mayor proporción de suelo limpio (imperv), mayor cantidad de
raccoons, woodchuchs y squirrels.

6.- Hay más woodchucks cuanta mayor cantidad de evergreen y suelo limpio
haya.

7.- Cuanta más proporción de low can haya menos ardillas hay pero si el
suelo está limpio hay más.

```{R I}

library(MASS)
fitglm.null <- glm.nb(I~1, data = datos, link = log)
summary(fitglm.null)
fitglm <- glm.nb(I ~ Raccon_VisR + Deer_VisR + Woodchuck_VisR + 
         Cat_VisR + Possum_VisR + Skunk_VisR + Squirrel_VisR + Number.tubes.peromyscus + ApproxMweeds + Number.tubes.raccoon + prop.imperv, data = datos, link=log)

summary(fitglm)

ci<-confint(fitglm)
pval<-as.numeric(format(round((coef(summary(fitglm))[,'Pr(>|z|)']),2), scientific = FALSE))
table.coef <- cbind(exp(cbind(OR=coef(fitglm),ci)), pval)
print(table.coef, digits = 4)
write.table(table.coef, "clipboard", sep="\t")
pR2 <- 1- fitglm$deviance / fitglm$null.deviance
pR2  
```

Analizando Ixodes hay una relación positiva con los tubos de los
mapaches

```{R H}
fitglm.null <- glm.nb(H~1, data = datos, link = log)
summary(fitglm.null)
fitglm <- glm.nb(H ~ Raccon_VisR + Deer_VisR + Woodchuck_VisR + 
         Cat_VisR + Possum_VisR + Skunk_VisR + Squirrel_VisR + Number.tubes.peromyscus + ApproxMweeds + Number.tubes.raccoon + prop.imperv, data = datos, link=log)

summary(fitglm)

ci<-confint(fitglm)
pval<-as.numeric(format(round((coef(summary(fitglm))[,'Pr(>|z|)']),2), scientific = FALSE))
table.coef <- cbind(exp(cbind(OR=coef(fitglm),ci)), pval)
print(table.coef, digits = 4)
write.table(table.coef, "clipboard", sep="\t")
pR2 <- 1- fitglm$deviance / fitglm$null.deviance
pR2  
```

En cuanto a las garrapatas Haemophilus solo es significativo los tubos
de los mapaches

```{R A}
fitglm.null <- glm.nb(A~1, data = datos, link = log)
summary(fitglm.null)
fitglm <- glm(A ~ Raccon_VisR + Deer_VisR + Woodchuck_VisR + 
         Cat_VisR + Possum_VisR + Skunk_VisR + Squirrel_VisR + Number.tubes.peromyscus + ApproxMweeds + Number.tubes.raccoon + prop.imperv, data = datos, link=log)

summary(fitglm)

ci<-confint(fitglm)
pval<-as.numeric(format(round((coef(summary(fitglm))[,'Pr(>|z|)']),2), scientific = FALSE))
table.coef <- cbind(exp(cbind(OR=coef(fitglm),ci)), pval)
print(table.coef, digits = 4)
write.table(table.coef, "clipboard", sep="\t")
pR2 <- 1- fitglm$deviance / fitglm$null.deviance
pR2  
```

En cuanto a las garrapatas A el significativo es los tubos de los
mapaches

```{R Gausiana}
#Ahora las distribuciones gausianas:
##Cat

fitglm.null <- glm.nb(Cat_VisR ~ 1, data = datos, link=log)
summary(fitglm.null)
fitglm <- glm.nb(Cat_VisR ~ Log.brush + Vegetable + ApproxMweeds, 
         data = datos, link=log)

summary(fitglm)
ci<-confint(fitglm)
pval<-as.numeric(format(round((coef(summary(fitglm))[,'Pr(>|z|)']),2), scientific = FALSE))
table.coef <- cbind(exp(cbind(OR=coef(fitglm),ci)), pval)
print(table.coef, digits = 4)
write.table(table.coef, "clipboard", sep="\t")
pR2 <- 1- fitglm$deviance / fitglm$null.deviance
pR2 

##Raccoon
fitglm.null <- glm.nb(Raccon_VisR ~ 1, data = datos, link=log)
summary(fitglm.null)
fitglm <- glm.nb(Raccon_VisR ~ prop.imperv + Lawn + ApproxMweeds + Log.brush, 
         data = datos, link=log)

summary(fitglm)
ci<-confint(fitglm)
pval<-as.numeric(format(round((coef(summary(fitglm))[,'Pr(>|z|)']),2), scientific = FALSE))
table.coef <- cbind(exp(cbind(OR=coef(fitglm),ci)), pval)
print(table.coef, digits = 4)
write.table(table.coef, "clipboard", sep="\t")
pR2 <- 1- fitglm$deviance / fitglm$null.deviance
pR2 

##Deer

fitglm.null <- glm.nb(Deer_VisR ~ 1, data = datos, link=log)
summary(fitglm.null)
fitglm <- glm.nb(Deer_VisR ~ Log.brush + Lawn, data = datos, link=log)

summary(fitglm)
ci<-confint(fitglm)
pval<-as.numeric(format(round((coef(summary(fitglm))[,'Pr(>|z|)']),2), scientific = FALSE))
table.coef <- cbind(exp(cbind(OR=coef(fitglm),ci)), pval)
print(table.coef, digits = 4)
write.table(table.coef, "clipboard", sep="\t")
pR2 <- 1- fitglm$deviance / fitglm$null.deviance
pR2 

##Woodchuck
fitglm.null <- glm.nb(Woodchuck_VisR ~ 1, data = datos, link=log)
summary(fitglm.null)
fitglm <- glm.nb(Woodchuck_VisR ~ ApproxMevergreen + prop.imperv + ApproxMweeds, 
         data = datos, link=log)

summary(fitglm)
ci<-confint(fitglm)
pval<-as.numeric(format(round((coef(summary(fitglm))[,'Pr(>|z|)']),2), scientific = FALSE))
table.coef <- cbind(exp(cbind(OR=coef(fitglm),ci)), pval)
print(table.coef, digits = 4)
write.table(table.coef, "clipboard", sep="\t")
pR2 <- 1- fitglm$deviance / fitglm$null.deviance
pR2 

##Squirrel
fitglm.null <- glm.nb(Squirrel_VisR ~ 1, data = datos, link=log)
summary(fitglm.null)
fitglm <- glm.nb(Squirrel_VisR ~ Log.brush + Lawn + prop.imperv + prop.lowcan, 
         data = datos, link=log)

summary(fitglm)
ci<-confint(fitglm)
pval<-as.numeric(format(round((coef(summary(fitglm))[,'Pr(>|z|)']),2), scientific = FALSE))
table.coef <- cbind(exp(cbind(OR=coef(fitglm),ci)), pval)
print(table.coef, digits = 4)
write.table(table.coef, "clipboard", sep="\t")
pR2 <- 1- fitglm$deviance / fitglm$null.deviance
pR2 
```
